apiVersion: jenkins.io/v1
kind: Environment
metadata:
  creationTimestamp: null
  labels:
    env: dev
    team: jx
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: dev
  namespace: jx
spec:
  kind: Development
  label: Development
  namespace: jx
  previewGitInfo:
    user: {}
  promotionStrategy: Never
  source:
    ref: master
    url: https://github.com/frog-network/jx3-gke-vault3.git
  teamSettings:
    appsRepository: http://chartmuseum.jenkins-x.io
    bootRequirements: |
      autoUpdate:
        enabled: false
        schedule: ""
      bootConfigURL: https://github.com/jenkins-x/jx3-boot-config
      buildPacks:
        buildPackLibrary:
          gitRef: master
          gitURL: https://github.com/jenkins-x/jx3-pipeline-catalog.git
      cluster:
        clusterName: neokube-test
        environmentGitOwner: todo
        gitKind: github
        gitName: github
        gitServer: https://github.com
        gke:
          projectNumber: "522234612266"
        namespace: jx
        project: neokube
        provider: gke
        registry: gcr.io
        vaultName: neokube-test
        vaultSAName: neokube-test-vt
        zone: europe-west1
      environments:
      - ingress:
          domain: 104.199.18.24.nip.io
          externalDNS: false
          namespaceSubDomain: -jx.
          tls:
            email: ""
            enabled: false
            production: true
        key: dev
        owner: frog-network
        repository: jx3-gke-vault3
      - ingress:
          domain: ""
          externalDNS: false
          namespaceSubDomain: ""
          tls:
            email: ""
            enabled: false
            production: false
        key: staging
      - ingress:
          domain: ""
          externalDNS: false
          namespaceSubDomain: ""
          tls:
            email: ""
            enabled: false
            production: false
        key: production
      gitops: true
      ingress:
        domain: 104.199.18.24.nip.io
        externalDNS: false
        ignoreLoadBalancer: true
        namespaceSubDomain: -jx.
        tls:
          email: ""
          enabled: false
          production: true
      kaniko: true
      pipelineUser:
        username: frog-network
      repository: nexus
      secretStorage: vault
      storage:
        backup:
          enabled: true
          url: gs://backup-neokube-test-ed6e73e6bd11
        logs:
          enabled: true
          url: gs://logs-neokube-test-ed6e73e6bd11
        reports:
          enabled: true
          url: gs://reports-neokube-test-ed6e73e6bd11
        repository:
          enabled: true
          url: gs://repository-neokube-test-ed6e73e6bd11
      vault:
        bucket: vault-neokube-test-ed6e73e6bd11
        key: crypto-key-neokube-test-ed6e73e6bd11
        keyring: keyring-neokube-test-ed6e73e6bd11
        name: neokube-test
        serviceAccount: neokube-test-vt
      velero:
        schedule: ""
        ttl: ""
      versionStream:
        ref: master
        url: https://github.com/jenkins-x/jxr-versions.git
      webhook: lighthouse
    buildPackRef: master
    buildPackUrl: https://github.com/jenkins-x/jx3-pipeline-catalog.git
    defaultScheduler:
      apiVersion: jenkins.io/v1
      kind: Scheduler
      name: jx-meta-pipeline
    dockerRegistryOrg: neokube
    envOrganisation: todo
    gitPublic: true
    gitServer: https://github.com
    helmTemplate: true
    importMode: YAML
    kubeProvider: gke
    pipelineUserEmail: jenkins-x@googlegroups.com
    pipelineUsername: frog-network
    promotionEngine: Prow
    prowConfig: Scheduler
    prowEngine: Tekton
    storageLocations:
      - bucketUrl: gs://logs-neokube-test-ed6e73e6bd11
        classifier: logs
      - bucketUrl: gs://reports-neokube-test-ed6e73e6bd11
        classifier: reports
    useGitOps: true
    versionStreamRef: master
    versionStreamUrl: https://github.com/jenkins-x/jxr-versions.git
  webHookEngine: Lighthouse
status: {}
