filepath: ""
environments:
  default:
    values:
    - versionStream/src/fake-secrets.yaml.gotmpl
    - jx-values-jx-staging.yaml
repositories:
- name: jenkins-x
  url: https://storage.googleapis.com/chartmuseum.jenkins-x.io
- name: external-secrets
  url: https://godaddy.github.io/kubernetes-external-secrets
- name: jx-labs
  url: https://storage.googleapis.com/jenkinsxio-labs-private/charts
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: banzaicloud-stable
  url: https://kubernetes-charts.banzaicloud.com
- name: jx3
  url: https://storage.googleapis.com/jenkinsxio/charts
- name: dev
  url: http://chartmuseum-jx.34.77.24.125.nip.io/
- name: kubecost
  url: https://kubecost.github.io/cost-analyzer/
releases:
- chart: dev/node-http
  version: 1.0.2
  name: node-http
  namespace: jx-staging
templates: {}
missingFileHandler: ""
