# Source: cost-analyzer/charts/grafana/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: kubecost-grafana
  labels:
    app: grafana
    chart: grafana-1.17.2
    heritage: Helm
    release: kubecost
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: kubecost
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubecost-grafana
subjects:
  - kind: ServiceAccount
    name: kubecost-grafana
