# Source: cost-analyzer/charts/grafana/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kubecost-grafana
  labels:
    app: grafana
    chart: grafana-1.17.2
    release: kubecost
    heritage: Helm
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: kubecost
spec:
  type: ClusterIP
  ports:
    - name: service
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: grafana
    release: kubecost
