# Source: kube-prometheus-stack/templates/prometheus/prometheus.yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: kps-kube-prometheus-stack-prometheus
  namespace: monitoring
  labels:
    app: kube-prometheus-stack-prometheus
    chart: kube-prometheus-stack-10.1.0
    release: "kps"
    heritage: "Helm"
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  alerting:
    alertmanagers:
      - namespace: monitoring
        name: kps-kube-prometheus-stack-alertmanager
        port: web
        pathPrefix: "/"
        apiVersion: v2
  baseImage: quay.io/prometheus/prometheus
  version: v2.21.0
  externalUrl: http://kps-kube-prometheus-stack-prometheus.monitoring:9090
  paused: false
  replicas: 1
  logLevel: info
  logFormat: logfmt
  listenLocal: false
  enableAdminAPI: false
  retention: "10d"
  routePrefix: "/"
  serviceAccountName: kps-kube-prometheus-stack-prometheus
  serviceMonitorSelector:
    matchLabels:
      release: "kps"
  serviceMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
      release: "kps"
  podMonitorNamespaceSelector: {}
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  ruleNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      app: kube-prometheus-stack
      release: "kps"
  portName: web
