# Source: kube-prometheus-stack/charts/grafana/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kps-grafana
  namespace: monitoring
  labels:
    helm.sh/chart: grafana-5.7.7
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: kps
    app.kubernetes.io/version: "7.2.0"
    app.kubernetes.io/managed-by: Helm
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  type: ClusterIP
  ports:
    - name: service
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: kps
