# Source: kube-prometheus-stack/templates/prometheus/prometheus.yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: kube-prometheus-stack-prometheus
  namespace: jx
  labels:
    app: kube-prometheus-stack-prometheus
    chart: kube-prometheus-stack-9.4.8
    release: "kube-prometheus-stack"
    heritage: "Helm"
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  alerting:
    alertmanagers:
      - namespace: jx
        name: kube-prometheus-stack-alertmanager
        port: web
        pathPrefix: "/"
        apiVersion: v2
  baseImage: quay.io/prometheus/prometheus
  version: v2.18.2
  externalUrl: http://kube-prometheus-stack-prometheus.jx:9090
  paused: false
  replicas: 1
  logLevel: info
  logFormat: logfmt
  listenLocal: false
  enableAdminAPI: false
  retention: "10d"
  routePrefix: "/"
  serviceAccountName: kube-prometheus-stack-prometheus
  serviceMonitorSelector:
    matchLabels:
      release: "kube-prometheus-stack"
  serviceMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
      release: "kube-prometheus-stack"
  podMonitorNamespaceSelector: {}
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  ruleNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      app: kube-prometheus-stack
      release: "kube-prometheus-stack"
  portName: web
