# Source: kube-prometheus-stack/templates/prometheus-operator/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kps-kube-prometheus-stack-operator
  labels:
    app: kube-prometheus-stack-operator
    chart: kube-prometheus-stack-10.1.0
    release: "kps"
    heritage: "Helm"
    gitops.jenkins-x.io/pipeline: 'cluster'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kps-kube-prometheus-stack-operator
subjects:
  - kind: ServiceAccount
    name: kps-kube-prometheus-stack-operator
    namespace: monitoring
