apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SourceConfig
metadata:
  creationTimestamp: null
spec:
  groups:
  - owner: frog-network
    provider: https://github.com
    providerKind: github
    repositories:
    - name: node-http
