# Source: kube-prometheus-stack/templates/prometheus-operator/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kps-kube-prometheus-stack-operator
  namespace: monitoring
  labels:
    app: kube-prometheus-stack-operator
    chart: kube-prometheus-stack-10.1.0
    release: "kps"
    heritage: "Helm"
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: https
      port: 443
      targetPort: https
  selector:
    app: kube-prometheus-stack-operator
    release: "kps"
  type: "ClusterIP"
