# Source: cost-analyzer/charts/prometheus/templates/alertmanager-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    component: "alertmanager"
    app: prometheus
    release: kubecost
    chart: prometheus-11.0.2
    heritage: Helm
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: kubecost-prometheus-alertmanager
  namespace: kubecost
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "2Gi"
