# Source: cost-analyzer/charts/prometheus/templates/alertmanager-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    component: "alertmanager"
    app: prometheus
    release: kubecost
    chart: prometheus-11.0.2
    heritage: Helm
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: kubecost-prometheus-alertmanager
  namespace: kubecost
data:
  alertmanager.yml: |
    global: {}
    receivers:
    - name: default-receiver
    route:
      group_interval: 5m
      group_wait: 10s
      receiver: default-receiver
      repeat_interval: 3h
