# Source: kube-prometheus-stack/charts/kube-state-metrics/templates/psp-clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kube-state-metrics
    helm.sh/chart: kube-state-metrics-2.8.14
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: kps
    gitops.jenkins-x.io/pipeline: 'cluster'
  name: psp-kps-kube-state-metrics
rules:
  - apiGroups: ['policy']
    resources: ['podsecuritypolicies']
    verbs: ['use']
    resourceNames:
      - kps-kube-state-metrics
