# Source: kube-prometheus-stack/templates/alertmanager/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kps-kube-prometheus-stack-alertmanager
  namespace: monitoring
  labels:
    app: kube-prometheus-stack-alertmanager
    self-monitor: "true"
    chart: kube-prometheus-stack-10.1.0
    release: "kps"
    heritage: "Helm"
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  ports:
    - name: web
      port: 9093
      targetPort: 9093
      protocol: TCP
  selector:
    app: alertmanager
    alertmanager: kps-kube-prometheus-stack-alertmanager
  type: "ClusterIP"
