# Source: kube-prometheus-stack/templates/grafana/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-prometheus-stack-grafana
  namespace: jx
  labels:
    app: kube-prometheus-stack-grafana
    chart: kube-prometheus-stack-9.4.8
    release: "kube-prometheus-stack"
    heritage: "Helm"
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
      app.kubernetes.io/instance: "kube-prometheus-stack"
  namespaceSelector:
    matchNames:
      - "jx"
  endpoints:
    - port: service
      path: "/metrics"
